# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:00:42+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class Address(BaseModel):
    addressId: str = Field(..., description='Address ID.')
    addressType: str = Field(..., description='Address type.')
    city: str = Field(..., description='Address city.')
    complement: str = Field(..., description='Address complement.')
    country: str = Field(..., description='Address country.')
    geoCoordinates: List[str] = Field(..., description='Geolocation coordinates.')
    neighborhood: str = Field(..., description='Address neighborhood.')
    number: str = Field(..., description='Address number.')
    postalCode: str = Field(..., description='Address postal code.')
    receiverName: str = Field(..., description='Address receiver name.')
    reference: str = Field(..., description='Address reference.')
    state: str = Field(..., description='Address state.')
    street: str = Field(..., description='Address street.')


class BRL(BaseModel):
    Count: int = Field(..., description='Count.')
    Facets: str = Field(..., description='Facets.')
    Max: int = Field(..., description='Maximum.')
    Mean: float = Field(..., description='Mean.')
    Min: int = Field(..., description='Minimum.')
    Missing: int = Field(..., description='Missing.')
    StdDev: float = Field(..., description='Standard deviation.')
    Sum: int = Field(..., description='Sum.')
    SumOfSquares: int = Field(..., description='Sum of squares.')


class BRL1(BaseModel):
    Count: int = Field(..., description='Count.')
    Facets: str = Field(..., description='Facets.')
    Max: int = Field(..., description='Maximum.')
    Mean: float = Field(..., description='Mean.')
    Min: int = Field(..., description='Minimum.')
    Missing: int = Field(..., description='Missing.')
    StdDev: float = Field(..., description='Standard deviation.')
    Sum: int = Field(..., description='Sum.')
    SumOfSquares: int = Field(..., description='Sum of squares.')


class ClientProfileData(BaseModel):
    corporateDocument: str = Field(
        ..., description='Company document, in case client is corporate.'
    )
    corporateName: str = Field(
        ..., description='Company name, in case client is corporate.'
    )
    corporatePhone: str = Field(
        ..., description='Company telephone number, in case client is corporate.'
    )
    customerClass: str = Field(..., description='Customer class.')
    document: str = Field(..., description='Client document.')
    documentType: str = Field(..., description='Client document type.')
    email: str = Field(..., description='Client email address.')
    firstName: str = Field(..., description='Client first name.')
    id: str = Field(..., description='Client ID.')
    isCorporate: bool = Field(..., description='Indicates whether client is corporate.')
    lastName: str = Field(..., description='Client last name.')
    phone: str = Field(..., description='Client telephone number.')
    stateInscription: str = Field(
        ..., description='Company state inscription, in case client is corporate.'
    )
    tradeName: str = Field(
        ..., description='Company trade name, in case client is corporate.'
    )
    userProfileId: str = Field(..., description='User profile ID.')


class CurrencyCode(BaseModel):
    BRL_1: BRL = Field(..., alias='BRL')


class CurrencyCode1(BaseModel):
    BRL: BRL1


class CurrencyFormatInfo(BaseModel):
    CurrencyDecimalDigits: int = Field(..., description='Currency decimal digits.')
    CurrencyDecimalSeparator: str = Field(
        ..., description='Currency decimal separator.'
    )
    CurrencyGroupSeparator: str = Field(..., description='Currency group separator.')
    CurrencyGroupSize: int = Field(..., description='Currency group size.')
    StartsWithCurrencySymbol: bool = Field(
        ...,
        description='Indicates whether value representations start with currency symbol.',
    )


class DeliveryId(BaseModel):
    courierId: str = Field(..., description='Courier ID.')
    courierName: str = Field(..., description='Courier name.')
    dockId: str = Field(..., description='Dock ID.')
    quantity: int = Field(..., description='Quantity.')
    warehouseId: str = Field(..., description='Warehouse ID.')


class Fulfillment(BaseModel):
    Count: int = Field(..., description='Count.')
    Facets: str = Field(..., description='Facets.')
    Max: int = Field(..., description='Maximum.')
    Mean: float = Field(..., description='Mean.')
    Min: int = Field(..., description='Minimum.')
    Missing: int = Field(..., description='Missing.')
    StdDev: float = Field(..., description='Standard deviation.')
    Sum: int = Field(..., description='Sum.')
    SumOfSquares: int = Field(..., description='Sum of squares.')


class Fulfillment1(BaseModel):
    Count: int = Field(..., description='Count.')
    Facets: str = Field(..., description='Facets.')
    Max: int = Field(..., description='Maximum.')
    Mean: float = Field(..., description='Mean.')
    Min: int = Field(..., description='Minimum.')
    Missing: int = Field(..., description='Missing.')
    StdDev: float = Field(..., description='Standard deviation.')
    Sum: int = Field(..., description='Sum.')
    SumOfSquares: int = Field(..., description='Sum of squares.')


class Item1(BaseModel):
    itemIndex: str = Field(
        ..., description='Index of the SKU being invoiced.', examples=[67]
    )
    price: int = Field(
        ...,
        description='Total price of the SKU being invoiced in cents. Do not use any decimal separator. For instance, `$24.99` should be represented as `2499`.',
        examples=[2499],
    )
    quantity: int = Field(
        ..., description='Quantity cof the SKU being invoiced.', examples=[3]
    )


class ItemsRemoved(BaseModel):
    id: str = Field(..., description='Id of removed item.')
    name: str = Field(..., description='Name of removed item.')
    price: int = Field(..., description='Removed items price in cents.')
    quantity: int = Field(..., description='Quantity of items removed.')
    unitMultiplier: str = Field(..., description='Removed item unit multiplier.')


class ListModel(BaseModel):
    ShippingEstimatedDate: str = Field(..., description='Shipping estimate date.')
    ShippingEstimatedDateMax: str = Field(
        ..., description='Maximum shipping estimate date.'
    )
    ShippingEstimatedDateMin: str = Field(
        ..., description='Minimum shipping estimate date.'
    )
    affiliateId: str = Field(
        ...,
        description='Three letter code indicating the marketplace in which the order was placed.',
    )
    authorizedDate: str = Field(..., description='Authorized date.')
    callCenterOperatorName: str = Field(..., description='Call center operator name.')
    clientName: str = Field(..., description='Client name.')
    creationDate: str = Field(..., description='Creation date.')
    currencyCode: str = Field(..., description='Currency code.')
    items: str = Field(..., description='Order items.')
    lastMessageUnread: str = Field(..., description='Last unread message.')
    listId: str = Field(..., description='List ID.')
    listType: str = Field(..., description='List type.')
    marketPlaceOrderId: str = Field(
        ..., description='ID of the order in the marketplace.'
    )
    orderId: str = Field(..., description='Order ID.')
    orderIsComplete: bool = Field(
        ..., description='Indicates whether order is complete.'
    )
    origin: str = Field(
        ..., description='Indicates whether order is marketplace, fulfillment or chain.'
    )
    paymentNames: str = Field(..., description='Order payment names.')
    salesChannel: str = Field(..., description='Sales channel.')
    sequence: str = Field(..., description='Order sequence number.')
    status: str = Field(..., description='Order status.')
    statusDescription: str = Field(..., description='Order status description.')
    totalItems: int = Field(..., description='Total items.')
    totalValue: int = Field(..., description='Order total value in cents.')
    workflowInErrorState: bool = Field(
        ..., description='Indicates whether order workflow is in error state.'
    )
    workflowInRetry: bool = Field(
        ..., description='Indicates whether workflow is in retry.'
    )


class Marketplace(BaseModel):
    baseURL: str = Field(..., description='Marketplace base URL.')
    isCertified: str = Field(
        ..., description='Indicates whether marketplace is certified.'
    )
    name: str = Field(..., description='Marketplace name.')


class Marketplace1(BaseModel):
    Count: int = Field(..., description='Count.')
    Facets: str = Field(..., description='Facets.')
    Max: int = Field(..., description='Maximum.')
    Mean: float = Field(..., description='Mean.')
    Min: int = Field(..., description='Minimum.')
    Missing: int = Field(..., description='Missing.')
    StdDev: float = Field(..., description='Standard deviation.')
    Sum: int = Field(..., description='Sum.')
    SumOfSquares: int = Field(..., description='Sum of squares.')


class Marketplace2(BaseModel):
    Count: int = Field(..., description='Count.')
    Facets: str = Field(..., description='Facets.')
    Max: int = Field(..., description='Maximum.')
    Mean: float = Field(..., description='Mean.')
    Min: int = Field(..., description='Minimum.')
    Missing: int = Field(..., description='Missing.')
    StdDev: float = Field(..., description='Standard deviation.')
    Sum: int = Field(..., description='Sum.')
    SumOfSquares: int = Field(..., description='Sum of squares.')


class Origin(BaseModel):
    Fulfillment_1: Fulfillment = Field(..., alias='Fulfillment')
    Marketplace: Marketplace1


class Origin1(BaseModel):
    Fulfillment: Fulfillment1
    Marketplace: Marketplace2


class Paging(BaseModel):
    currentPage: int = Field(..., description='Current returned page.')
    pages: int = Field(..., description='Number of pages.')
    perPage: int = Field(..., description='Number of items returned per page.')
    total: int = Field(..., description='Paging total.')


class Payment(BaseModel):
    cardHolder: str = Field(..., description='Card holder')
    cardNumber: str = Field(..., description='Card number.')
    connectorResponses: Dict[str, Any] = Field(..., description='Connector responses.')
    cvv2: str = Field(..., description='Card verification code.')
    dueDate: str = Field(..., description='Due date.')
    expireMonth: str = Field(..., description='Card expiration month.')
    expireYear: str = Field(..., description='Card expiration year.')
    firstDigits: str = Field(..., description='Card first digits.')
    giftCardCaption: str = Field(..., description='Gift card caption.')
    giftCardId: str = Field(..., description='Gift card ID.')
    giftCardName: str = Field(..., description='Gift card name.')
    group: str = Field(..., description='Payment group.')
    id: str = Field(..., description='Payment ID.')
    installments: int = Field(..., description='Payment installments.')
    lastDigits: str = Field(..., description='Card last digits.')
    paymentSystem: str = Field(..., description='Payment system.')
    paymentSystemName: str = Field(..., description='Payment system name.')
    redemptionCode: str = Field(..., description='Redemption code.')
    referenceValue: int = Field(
        ..., description='Reference value for interest calculation in cents.'
    )
    tid: str = Field(..., description='Payment TID.')
    url: str = Field(..., description='Payment URL.')
    value: int = Field(..., description='Payment value in cents.')


class PickupStoreInfo(BaseModel):
    additionalInfo: str = Field(..., description='Pickup additional information.')
    address: str = Field(..., description='Pickup address.')
    dockId: str = Field(..., description='Pickup dock ID.')
    friendlyName: str = Field(..., description='Pickup friendly name.')
    isPickupStore: bool = Field(
        ..., description='Indicates whether it is pickup store.'
    )


class RatesAndBenefitsData(BaseModel):
    id: str = Field(..., description='Field ID.')
    rateAndBenefitsIdentifiers: List[str] = Field(
        ..., description='Array with rates and benefits IDs.'
    )


class Receipt(BaseModel):
    date: str = Field(..., description='Date.')
    orderId: str = Field(..., description='Order ID.')
    receipt: str = Field(..., description='Receipt.')


class SelectedAddress(RootModel[Address]):
    root: Address


class Seller(BaseModel):
    id: str = Field(..., description='Seller ID.')
    logo: str = Field(..., description='Seller logo.')
    name: str = Field(..., description='Seller name.')


class Sla(BaseModel):
    deliveryChannel: str = Field(..., description='SLA delivery channel.')
    deliveryWindow: str = Field(..., description='SLA delivery window.')
    id: str = Field(..., description='SLA ID.')
    name: str = Field(..., description='SLA name.')
    pickupStoreInfo: PickupStoreInfo
    polygonName: str = Field(..., description='SLA polygon name.')
    price: int = Field(..., description='SLA price in cents.')
    shippingEstimate: str = Field(..., description='SLA shipping estimate.')


class StorePreferencesData(BaseModel):
    countryCode: str = Field(..., description='Three letter ISO country code.')
    currencyCode: str = Field(..., description='Currency code.')
    currencyFormatInfo: CurrencyFormatInfo
    currencyLocale: int = Field(..., description='Currency locale.')
    currencySymbol: str = Field(..., description='Currency symbol.')
    timeZone: str = Field(..., description='Time zone.')


class TotalItems(BaseModel):
    Count: int = Field(..., description='Count.')
    Facets: str = Field(..., description='Facets.')
    Max: int = Field(..., description='Maximum.')
    Mean: float = Field(..., description='Mean.')
    Min: int = Field(..., description='Minimum.')
    Missing: int = Field(..., description='Missing.')
    StdDev: float = Field(..., description='Standard deviation.')
    Sum: int = Field(..., description='Sum.')
    SumOfSquares: int = Field(..., description='Sum of squares.')


class Transaction(BaseModel):
    isActive: bool = Field(..., description='Indicates whether transaction is active.')
    merchantName: str = Field(..., description='Merchant name.')
    payments: List[Payment] = Field(
        ..., description='Array with information on each payment for the order.'
    )
    transactionId: str = Field(..., description='Transaction ID.')


class ApiOrdersExtendsearchOrdersPostRequest(BaseModel):
    f_creationDate: str = Field(
        ...,
        description='Concatened value sufix {{creationDate}} and range date in Timestamp format.',
        examples=[
            'creationDate:[2021-11-01T00:00:00.000Z TO 2022-11-10T02:00:00.000Z]'
        ],
    )
    page: int = Field(
        ..., description='Number of the page to be retrieved.', examples=[1]
    )
    per_page: int = Field(..., description='Number of orders per page.', examples=[15])
    q: Optional[str] = Field(
        None, description='Full-text search for the orders.', examples=['Postman Test']
    )


class AdditionalInfo(BaseModel):
    brandId: Optional[str] = Field(None, description='Brand ID.')
    brandName: Optional[str] = Field(None, description='Brand name.')
    dimension: Optional[str] = Field(None, description='Dimension.')
    offeringInfo: Optional[str] = Field(None, description='Offering information.')
    offeringType: Optional[str] = Field(None, description='Offering type.')
    offeringTypeId: Optional[str] = Field(None, description='Offering type ID.')


class BundleItem(BaseModel):
    id: Optional[int] = Field(None, description='Service identifier.')
    name: Optional[str] = Field(None, description='Name.')
    price: Optional[int] = Field(None, description='Price in cents.')
    type: Optional[str] = Field(None, description='Type')


class SellingPrice(BaseModel):
    quantity: Optional[int] = Field(None, description='Quantity.')
    value: Optional[int] = Field(None, description='Value in cents.')


class PriceDefinition(BaseModel):
    calculatedSellingPrice: Optional[int] = Field(
        None, description='Calculated selling price in cents.'
    )
    sellingPrices: Optional[List[SellingPrice]] = Field(
        None, description='Selling prices.'
    )
    total: Optional[int] = Field(None, description='Total in cents.')


class PriceTag(BaseModel):
    identifier: Optional[str] = Field(None, description='Price tag identifier.')
    isPercentual: Optional[bool] = Field(
        None,
        description='Indicates whether price tag value is applied through a percentage.',
    )
    name: Optional[str] = Field(None, description='Name.')
    rawValue: Optional[int] = Field(None, description='Raw value.')
    value: Optional[int] = Field(None, description='Value.')


class ProductCategories(BaseModel):
    field_ID_: Optional[str] = Field(
        None,
        alias='{ID}',
        description='Product category corresponding to the ID in the field key.',
    )


class Item(BaseModel):
    additionalInfo: Optional[AdditionalInfo] = Field(
        None, description='Additional information.'
    )
    attachments: Optional[List[str]] = Field(
        None, description='Array containing information on attachments.'
    )
    availability: Optional[str] = Field(None, description='Availability')
    bundleItems: Optional[List[BundleItem]] = Field(
        None,
        description='Information on services sold along with the SKU. Example: a gift package.',
    )
    detailUrl: Optional[str] = Field(None, description='Detail URL.')
    ean: Optional[str] = Field(None, description='European Article Number.')
    id: Optional[str] = Field(None, description='ID.')
    imageUrl: Optional[str] = Field(None, description='Image URL.')
    isGift: Optional[bool] = Field(
        None, description='Indicates whether item is a gift.'
    )
    listPrice: Optional[int] = Field(None, description='List price in cents.')
    manualPrice: Optional[int] = Field(None, description='Manual price in cents.')
    manualPriceAppliedBy: Optional[str] = Field(
        None, description='User that applied the manual price, if that is the case.'
    )
    manufacturerCode: Optional[str] = Field(None, description='Manufacturer code.')
    measurementUnit: Optional[str] = Field(None, description='Measurement unit')
    modalType: Optional[str] = Field(None, description='Modal type.')
    name: Optional[str] = Field(None, description='Name.')
    parentAssemblyBinding: Optional[str] = Field(
        None, description='Parent assembly binding.'
    )
    parentItemIndex: Optional[int] = Field(None, description='Parent item index.')
    preSaleDate: Optional[str] = Field(None, description='Presale date.')
    price: Optional[int] = Field(None, description='Price in cents.')
    priceDefinition: Optional[PriceDefinition] = Field(
        None, description='Price information.'
    )
    priceTags: Optional[List[PriceTag]] = Field(
        None,
        description='Array of price tags, each of which, modifies the price in some way, like discounts or rates that apply to the item in the context of the order.',
    )
    priceValidUntil: Optional[str] = Field(
        None, description='Price expiration date and time.'
    )
    productCategories: Optional[ProductCategories] = Field(
        None, description='Object, where each field is an ID from `productCategoryIds.'
    )
    productCategoryIds: Optional[str] = Field(None, description='Product category IDs.')
    productId: Optional[str] = Field(None, description='Product ID.')
    productRefId: Optional[str] = Field(None, description='Product Ref ID.')
    quantity: Optional[int] = Field(None, description='Quantity.')
    refId: Optional[str] = Field(None, description='Ref ID.')
    rewardValue: Optional[int] = Field(None, description='Reward value in cents.')
    seller: Optional[str] = Field(None, description='Seller.')
    sellerChain: Optional[List[str]] = Field(
        None,
        description='Sellers involved in the chain. The list should contain only one seller, unless it is a [Multilevel Omnichannel Inventory](https://help.vtex.com/pt/tutorial/multilevel-omnichannel-inventory--7M1xyCZWUyCB7PcjNtOyw4) order.',
    )
    sellingPrice: Optional[int] = Field(
        None,
        description='Selling price in cents. Note that this field may be subject to rounding discrepancies. We recommend retrieving data from the `priceDefinition` data structure instead.',
    )
    skuName: Optional[str] = Field(None, description='SKU name.')
    tax: Optional[int] = Field(None, description='Tax value in cents.')
    uniqueId: Optional[str] = Field(None, description="Order's item unique ID.")
    unitMultiplier: Optional[int] = Field(None, description='Unit multiplier')


class Item2(BaseModel):
    description: Optional[str] = Field(None, description='Item description.')
    itemIndex: Optional[int] = Field(
        None,
        description='Item index in reference to the position of the item in the `items` array.',
    )
    price: Optional[int] = Field(None, description='Item price in cents.')
    quantity: Optional[int] = Field(None, description='Item quantity.')
    unitMultiplier: Optional[float] = Field(None, description='Item unit multiplier.')


class Item3(BaseModel):
    itemIndex: Optional[str] = Field(
        None,
        description='Item index corresponding to the position of the item in the main `items` array.',
    )
    quantity: Optional[int] = Field(None, description='Quantity.')


class Refund(BaseModel):
    items: Optional[List[Item3]] = Field(None, description='Information on items.')


class Restitutions(BaseModel):
    refund: Optional[Refund] = Field(None, description='Information on refunds.')


class Package(BaseModel):
    cfop: Optional[str] = Field(None, description='Fiscal operation code.')
    courier: Optional[str] = Field(None, description='Courier.')
    courierStatus: Optional[str] = Field(None, description='Courier status.')
    embeddedInvoice: Optional[str] = Field(None, description='Embedded voice in XML.')
    invoiceKey: Optional[str] = Field(None, description='Invoice key.')
    invoiceNumber: Optional[str] = Field(None, description='Invoice number.')
    invoiceUrl: Optional[str] = Field(None, description='Invoice URL.')
    invoiceValue: Optional[int] = Field(None, description='Invoice value in cents.')
    issuanceDate: Optional[str] = Field(None, description='Issuance date.')
    items: Optional[List[Item2]] = Field(
        None, description='Information on each item in the package.'
    )
    restitutions: Optional[Restitutions] = Field(
        None,
        description='Information on how restitutions are to be made to the customer, in case of a return (invoice `type` is `input`).',
    )
    trackingNumber: Optional[str] = Field(None, description='Tracking number.')
    trackingUrl: Optional[str] = Field(None, description='Tracking URL.')
    type: Optional[str] = Field(
        None, description='Invoice type `Output` for sales and `Input` for returns.'
    )
    volumes: Optional[int] = Field(
        None, description='Quantity of packages involved in the order.'
    )


class PackageAttachment(BaseModel):
    packages: Optional[List[Package]] = Field(
        None, description='Information on each package.'
    )


class Total(BaseModel):
    id: Optional[str] = Field(
        None, description="Order's total ID.", examples=['Discounts']
    )
    name: Optional[str] = Field(
        None, description="Order's total name.", examples=['Discount total.']
    )
    value: Optional[int] = Field(
        None, description="Order's total value.", examples=[199]
    )


class ApiOrdersPvtDocumentOrderIdCancelPostRequest(BaseModel):
    reason: Optional[str] = Field(
        None,
        description='Reason for cancelling the order.',
        examples=['Unexpected stock shortage'],
    )


class ApiOrdersPvtDocumentOrderIdCancelPostResponse(BaseModel):
    date: Optional[str] = Field(
        None, description='Date and time when the notification was received.'
    )
    orderId: Optional[str] = Field(
        None, description='Identification of the order in the seller.'
    )
    receipt: Optional[str] = Field(
        None, description='Protocol code generated by the update. It may be `null`.'
    )


class ApiOrdersPvtDocumentOrderIdInvoicesPostResponse(BaseModel):
    date: Optional[str] = Field(
        None, description='Date and time when the notification was received.'
    )
    orderId: Optional[str] = Field(
        None, description='Identification of the order in the seller.'
    )
    receipt: Optional[str] = Field(
        None, description='Protocol code generated by the update. It may be `null`.'
    )


class ChangesDatum(BaseModel):
    discountValue: int = Field(..., description='Discount value in cents.')
    incrementValue: int = Field(..., description='Order value increment in cents.')
    itemsAdded: List[str] = Field(
        ..., description='Array with information on items added to the order.'
    )
    itemsRemoved: List[ItemsRemoved] = Field(
        ..., description='Array with information on items removed from the order.'
    )
    reason: str = Field(..., description='Change reason.')
    receipt: Receipt


class Facets(BaseModel):
    currencyCode: CurrencyCode
    origin: Origin


class Facets1(BaseModel):
    currencyCode: CurrencyCode1
    origin: Origin1


class InvoiceNotificationRequest(BaseModel):
    cfop: Optional[str] = Field(
        None, description='Fiscal code used in Brazil.', examples=['6.104']
    )
    courier: Optional[str] = Field(
        None,
        description='The name of the carrier responsible for delivering the order.\n\r> This field should only be used when sending **tracking** information. When the request is used for sending the invoice, this field should be left empty (`""`).',
    )
    extraValue: Optional[int] = Field(
        None,
        description='Extra value in the invoice in cents. Do not use any decimal separator. For instance, `$24.99` should be represented as `2499`.',
        examples=[100],
    )
    invoiceKey: Optional[str] = Field(None, description='Invoice key.')
    invoiceNumber: str = Field(
        ..., description='Number that identifies the invoice.', examples=['123456789']
    )
    invoiceUrl: Optional[str] = Field(
        None,
        description='URL of the invoice. Can be used to send the URL of an XML file, for example, which is useful for some integrations.',
    )
    invoiceValue: str = Field(
        ...,
        description='Total amount being invoiced in cents. Do not use any decimal separator. For instance, `$24.99` should be represented as `2499`.',
        examples=[2499],
    )
    issuedDate: str = Field(
        ...,
        description='Issuance date of the invoice in ISO format.',
        examples=['2020-07-15'],
    )
    items: List[Item1] = Field(
        ..., description='Array containing the SKUs that are being invoiced.'
    )
    trackingNumber: Optional[str] = Field(
        None,
        description='Code that identifies the order tracking.\n\r> This field should only be used when sending the **tracking** information. When the request is used for sending the invoice, this field should be left empty (`""`).',
    )
    trackingUrl: Optional[str] = Field(
        None,
        description='URL used to track the order.\n\r> This field should only be used when sending the **tracking** information. When the request is used for sending the invoice, this field should be left empty (`""`).',
    )
    type: str = Field(
        ...,
        description='The type of invoice. There are two possible values: `"Output"` and `"Input"`. The `"Output"` type should be used when the invoice you are sending is a selling invoice. The `"Input"` type should be used when you send a return invoice.',
        examples=['Output'],
    )
    volumes: Optional[int] = Field(
        None, description='Number of volumes in the invoice.', examples=[3]
    )


class LogisticsInfo(BaseModel):
    addressId: str = Field(..., description='Address ID.')
    deliveryChannel: str = Field(..., description='Delivery channel.')
    deliveryCompany: str = Field(..., description='Delivery company.')
    deliveryIds: List[DeliveryId] = Field(..., description='Array of delivery IDs.')
    deliveryWindow: str = Field(..., description='Delivery window information.')
    itemIndex: int = Field(
        ..., description='Item index, matching the index in the `items` array.'
    )
    listPrice: int = Field(..., description='List price in cents.')
    lockTTL: str = Field(..., description='Reservation lasting period.')
    pickupStoreInfo: PickupStoreInfo
    polygonName: str = Field(..., description='Polygon name.')
    price: int = Field(..., description='Prince in cents.')
    selectedSla: str = Field(..., description='Selected SLA.')
    sellingPrice: int = Field(..., description='Selling price in cents.')
    shippingEstimate: str = Field(..., description='Shipping estimate.')
    shippingEstimateDate: str = Field(..., description='Shipping estimate date.')
    shipsTo: List[str] = Field(
        ...,
        description='List of countries (three letter ISO code) to which shipping is available.',
    )
    slas: List[Sla] = Field(..., description='Array with information on the SLAs.')


class PaymentData(BaseModel):
    transactions: List[Transaction] = Field(
        ..., description='Array with information on each transaction of the order.'
    )


class ShippingData(BaseModel):
    address: Address
    id: str = Field(..., description='Field ID.')
    logisticsInfo: List[LogisticsInfo] = Field(
        ..., description='Array with logistics information of each item in the order.'
    )
    selectedAddresses: List[SelectedAddress] = Field(
        ..., description="Array of the selected addresses' information."
    )
    trackingHints: str = Field(..., description='Tracking hints.')


class TotalValue(BaseModel):
    Count: int = Field(..., description='Value count.')
    Facets_1: Facets = Field(..., alias='Facets')
    Max: int = Field(..., description='Value maximum.')
    Mean: float = Field(..., description='Value mean.')
    Min: int = Field(..., description='Value minimum.')
    Missing: int = Field(..., description='Missing values.')
    StdDev: float = Field(..., description='Values standard deviation.')
    Sum: int = Field(..., description='Values sum.')
    SumOfSquares: int = Field(..., description='Values sum of squares')


class ChangesAttachment(BaseModel):
    changesData: List[ChangesDatum] = Field(
        ..., description='Array with data on order changes.'
    )
    id: str = Field(..., description='Change ID.')


class Stats1(BaseModel):
    totalItems: TotalItems
    totalValue: TotalValue


class ApiOrdersPvtDocumentOrderIdGetResponse(BaseModel):
    affiliateId: Optional[str] = Field(
        None,
        description='Three letter code identifying the marketplace where the order was placed.',
        examples=['ABC'],
    )
    allowCancellation: Optional[bool] = Field(
        None, description='Indicates whether cancelation is allowed for the order.'
    )
    allowEdition: Optional[bool] = Field(
        None, description='Indicates whether edition is allowed for the order.'
    )
    approvedBy: Optional[str] = Field(
        None,
        description='User that approved the order, in case of manual approval.',
        examples=['alex@store.com'],
    )
    authorizedDate: Optional[str] = Field(
        None, description='Date in which the order was authorized in UTC.'
    )
    callCenterOperatorData: Optional[str] = Field(
        None, description='Call center operator data.'
    )
    cancelReason: Optional[str] = Field(
        None, description='Reason for cancelation.', examples=['Stock shortage.']
    )
    cancelledBy: Optional[str] = Field(
        None, description='User that canceled the order.', examples=['alex@store.com']
    )
    changesAttachment: Optional[ChangesAttachment] = None
    clientProfileData: Optional[ClientProfileData] = None
    commercialConditionData: Optional[str] = Field(
        None, description='Commercial condition data.'
    )
    creationDate: Optional[str] = Field(
        None, description='Creation date.', examples=['2019-01-28T20:09:43+00:00']
    )
    customData: Optional[str] = Field(None, description='Custom data.')
    emailTracked: Optional[str] = Field(
        None, description='Email tracked.', examples=['clark.kent@example.com']
    )
    followUpEmail: Optional[str] = Field(None, description='Follow up email.')
    giftRegistryData: Optional[str] = Field(None, description='Gift registry data.')
    hostname: Optional[str] = Field(None, description='Host name.')
    invoiceData: Optional[Dict[str, Any]] = Field(
        None, description="Information pertinent to the order's invoice."
    )
    invoicedDate: Optional[str] = Field(
        None, description='Date in which the order was invoiced in UTC.'
    )
    isCheckedIn: Optional[bool] = Field(
        None, description='Indicates whether client is checked in.'
    )
    isCompleted: Optional[bool] = Field(
        None, description='Indicates whether order is completed.'
    )
    items: Optional[List[Item]] = Field(
        None, description='Information on each item in the order.'
    )
    lastChange: Optional[str] = Field(
        None,
        description='Date of last change.',
        examples=['2019-02-06T20:46:11.7010747+00:00'],
    )
    lastMessage: Optional[str] = Field(None, description='Last message.')
    marketingData: Optional[str] = Field(None, description='Marketing data.')
    marketplace: Optional[Marketplace] = None
    marketplaceItems: Optional[List[str]] = Field(
        None, description='Marketplace items.'
    )
    marketplaceOrderId: Optional[str] = Field(
        None,
        description='ID of the order in the marketplace.',
        examples=['ABC-v5195004lux-01'],
    )
    marketplaceServicesEndpoint: Optional[str] = Field(
        None,
        description='Marketplace endpoint for post purchase communication.',
        examples=['http://oms.vtexinternal.com.br/api/oms?an=luxstore'],
    )
    merchantName: Optional[str] = Field(
        None, description='Merchant name.', examples=['luxstore']
    )
    openTextField: Optional[str] = Field(None, description='Open text field.')
    orderFormId: Optional[str] = Field(
        None, description='ID of the shopping cart from which the order was created.'
    )
    orderGroup: Optional[str] = Field(None, description='Order group.', examples=['00'])
    orderId: Optional[str] = Field(
        None, description='Order ID.', examples=['v5195004lux-01']
    )
    origin: Optional[str] = Field(None, description='Origin.', examples=['Marketplace'])
    packageAttachment: Optional[PackageAttachment] = Field(
        None, description='Package attachment.', examples=[{'packages': []}]
    )
    paymentData: Optional[PaymentData] = None
    ratesAndBenefitsData: Optional[RatesAndBenefitsData] = None
    roundingError: Optional[int] = Field(None, description='Rounding error in cents.')
    salesChannel: Optional[str] = Field(
        None, description='Sales channel.', examples=['1']
    )
    sellerOrderId: Optional[str] = Field(
        None, description='Seller order ID.', examples=['00-v5195004lux-01']
    )
    sellers: Optional[List[Seller]] = Field(
        None, description='Array with sellers information.'
    )
    sequence: Optional[str] = Field(
        None, description='Sequence number.', examples=['502556']
    )
    shippingData: Optional[ShippingData] = None
    status: Optional[str] = Field(
        None, description='Status in the order workflow.', examples=['invoiced']
    )
    statusDescription: Optional[str] = Field(
        None,
        description='Status description which is displayed on the Admin panel.',
        examples=['Faturado'],
    )
    storePreferencesData: Optional[StorePreferencesData] = None
    totals: Optional[List[Total]] = Field(
        None, description="Information on each of the order's totals."
    )
    value: Optional[int] = Field(None, description='Value in cents.', examples=[2499])


class Stats(BaseModel):
    stats: Stats1


class ListOrders(BaseModel):
    facets: List[str] = Field(..., description='Array of facets.')
    list: List[ListModel] = Field(
        ..., description='Array containing information on orders listed.'
    )
    paging: Paging
    stats: Stats
